[build]
  publish = "dist/portfolio-web-aronbo-ng/browser"
  command = "npx ng build --configuration production"

[build.environment]
  NODE_VERSION = "22"
  NPM_CONFIG_PREFER_ONLINE = "true"
  NPM_CONFIG_CACHE = "/dev/null"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.production.environment]
NODE_ENV = "production"