[build]
  publish = "dist/portfolio-web-aronbo-ng/browser"
  command = "npx ng build --configuration production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.production.environment]
NODE_ENV = "production"